### ISSUE TITLE
Essay Question Capability

### ISSUE THREAD

**Issue by lwshaffer25** [Prendus/assessml#7]
This is the #1 factor in increased sales right now from speaking with professors
From talking with them, I recommend having it set up so that users select "create a question," then choose a question type (essay/multiple choice for now, but they also want fill-in-the-blank and true/false). For essays, we should walk students through writing a prompt, then creating a rubric. 
[_I'm not sure exactly how we'd want to do that, but I think it could be pointing out important elements of a rubric (like identifying elements of form and function and assigning weight to each). The key thing is that instructors want the rubric to be a way for students to think for themselves. As they create a rubric, they have to identify what's most important._]
Instructors want rubrics to be hidden, so that only prompt writers can view them. After students write essays, they should submit them, at which point the prompt writer is notified that their prompt has been answered and returns to Prendus to review the essay, then "grade" it. It would still be done for a completion grade, but it's essential that students receive the feedback on their essays.

**Comment by lastmjs** [comment]
Right now you can add little inputs like this: `[input]`. I'm wondering if we can allow for short answers (more of a textarea or something) with another input syntax, maybe: `[long-input]`. Maybe we should change the names to `[short-input]` and `[long-input]`. Any ideas?

**Comment by lastmjs** [comment]
I've added this with the `[essay]` tag
