### ISSUE TITLE
Math Palette

### ISSUE THREAD

**Issue by lwshaffer25** [Prendus/assessml#8]
- [ ] Superscript and subscript
- [ ] Italics
- [ ] Plus or Minus
- [ ] Relationships 
- [ ] Congruence 
- [ ] Multiplication dot 
- [ ] Multiplication cross 
- [ ] Direct sum 
- [ ] Subset 
- [ ] Proper subset 
- [ ] Empty set 
- [ ] Infinity 
- [ ] Some Greek letters (for econ, we’ll actually want all of them, so it’d be good to do that if we could)
- [ ] Proof symbols 
- [ ] Fraction palette 
- [ ] Matrix palette 
- [ ] Bar and vector palette
- [ ] Absolute value palette
- [ ] Square root palette

**Comment by lastmjs** [comment]
I just want to make sure we include absolutely only the absolute necessary symbols...how do we know these are the symbols that should be included?

**Comment by lwshaffer25** [comment]
This is a list from the math professor that will be using it in her
abstract algebra class. If she likes it, we'll get all of BYU-I calculus in
a matter of time, because the online classes follow what she does in her
class (as the one that wrote their curriculum).

Luke Shaffer
Chief Operations Officer | Prendus
